apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
secrets:
  - name: git-secret
  - name: registry-credentials
  - name: tap-registry
imagePullSecrets:
  - name: registry-credentials
  - name: tap-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-deliverable
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAArAAAABNlY2RzYS
    1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQAOXbV78L6LcWm72nWeMt8k+2RTyzr
    +o7oEYnqc57qBORlnWpF/r7o7gr52zK21GWOXT77pV/c9j5IGhWPLm6wYsIBOCST1wqn0g
    /d+O+S3VaatNl2s37cg4dpku2iKqRpNqMytQyXTJZmSTWXINIKGLaXO4jw2Gy5HcW04EkG
    0WEJGt8AAAEAVD5bOVQ+WzkAAAATZWNkc2Etc2hhMi1uaXN0cDUyMQAAAAhuaXN0cDUyMQ
    AAAIUEADl21e/C+i3Fpu9p1njLfJPtkU8s6/qO6BGJ6nOe6gTkZZ1qRf6+6O4K+dsyttRl
    jl0++6Vf3PY+SBoVjy5usGLCATgkk9cKp9IP3fjvkt1WmrTZdrN+3IOHaZLtoiqkaTajMr
    UMl0yWZkk1lyDSChi2lzuI8NhsuR3FtOBJBtFhCRrfAAAAQT8TmiPEqP3gnqYYDnrIdnO8
    M4S/9vRZUU/P6Cw0+jdURuCYlcCGAhnGsZX0E4cuU+mkkhu9bekNNToHcgjQD/LJAAAAAA
    ECAw==
    -----END OPENSSH PRIVATE KEY-----
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAArAAAABNlY2RzYS
    1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQAOXbV78L6LcWm72nWeMt8k+2RTyzr
    +o7oEYnqc57qBORlnWpF/r7o7gr52zK21GWOXT77pV/c9j5IGhWPLm6wYsIBOCST1wqn0g
    /d+O+S3VaatNl2s37cg4dpku2iKqRpNqMytQyXTJZmSTWXINIKGLaXO4jw2Gy5HcW04EkG
    0WEJGt8AAAEAVD5bOVQ+WzkAAAATZWNkc2Etc2hhMi1uaXN0cDUyMQAAAAhuaXN0cDUyMQ
    AAAIUEADl21e/C+i3Fpu9p1njLfJPtkU8s6/qO6BGJ6nOe6gTkZZ1qRf6+6O4K+dsyttRl
    jl0++6Vf3PY+SBoVjy5usGLCATgkk9cKp9IP3fjvkt1WmrTZdrN+3IOHaZLtoiqkaTajMr
    UMl0yWZkk1lyDSChi2lzuI8NhsuR3FtOBJBtFhCRrfAAAAQT8TmiPEqP3gnqYYDnrIdnO8
    M4S/9vRZUU/P6Cw0+jdURuCYlcCGAhnGsZX0E4cuU+mkkhu9bekNNToHcgjQD/LJAAAAAA
    ECAw==
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAA5dtXvwvotxabvadZ4y3yT7ZFPLOv6jugRiepznuoE5GWdakX+vujuCvnbMrbUZY5dPvulX9z2PkgaFY8ubrBiwgE4JJPXCqfSD93475LdVpq02XazftyDh2mS7aIqpGk2ozK1DJdMlmZJNZcg0goYtpc7iPDYbLkdxbTgSQbRYQka3w==
  known_hosts: |
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl